name: Bug report
title: '[Bug]: '
labels: ['bug']
projects: ['stijnpiron/6']
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the issue
    validations:
      required: true
  - type: textarea
    id: current_behavior
    attributes:
      label: Current behavior
      description: Current behavior
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce
      placeholder: 1. Go to...
    validations:
      required: true
  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: technical_context
    attributes:
      label: Technical context
      description: Technical context
  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance criteria
      description: Acceptance criteria
